"""Update table Product

Revision ID: 87403f21f762
Revises: 75165af71a80
Create Date: 2025-09-24 12:35:16.510102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87403f21f762'
down_revision: Union[str, Sequence[str], None] = '75165af71a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Очистка таблицы products перед добавлением нового столбца
    op.execute("DELETE FROM products")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
